name: Build YimMenuV2Launcher

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup MSBuild path
        uses: microsoft/setup-msbuild@v2

      - name: Build solution
        run: msbuild YimMenuV2LauncherOpenSource.sln /p:Configuration=Release

      - name: Upload EXE Artifact
        uses: actions/upload-artifact@v4
        with:
          name: YimMenuV2LauncherExe
          path: |
            **\*.exe
