name: Build YimMenuV2Launcher

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install vcpkg & dependencies
        run: |
          git clone https://github.com/microsoft/vcpkg.git
          .\vcpkg\bootstrap-vcpkg.bat
          .\vcpkg\vcpkg install

      - name: Set VCPKG_ROOT environment variable
        run: echo "VCPKG_ROOT=$(pwd)/vcpkg" >> $GITHUB_ENV

      - uses: microsoft/setup-msbuild@v2

      - name: Build solution
        run: msbuild YimMenuV2LauncherOpenSource.sln /p:Configuration=Release
